CREATE DATABASE IF NOT EXISTS book
  CHARACTER SET utf8mb4 COLLATE  utf8mb4_unicode_ci;
USE book;

CREATE TABLE IF NOT EXISTS book (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(225) NOT NULL,
  author VARCHAR(225) NOT NULL,
  year INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);